Repository Project-MONAI/monai-deploy-workflow-manager, pull requests merged in 2022-06, with the labels that each got.

#153 add update workflow endpoint
  src/Common/Interfaces/IWorkflowService.cs
  src/Common/Services/WorkflowService.cs
  src/Database/Interfaces/IWorkflowRepository.cs
  src/Database/WorkflowRepository.cs
  src/WorkflowManager/Controllers/WorkflowsController.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Features/WorkflowApi.feature
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Features/WorkflowApi.feature.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Features/WorkflowUpdateAPI.feature
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Features/WorkflowUpdateAPI.feature.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Hooks.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/StepDefinitions/ApiStepDefinitions.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/StepDefinitions/TaskStatusUpdateStepDefinitions.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/StepDefinitions/WorkflowRequestStepDefinitions.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Support/Assertions.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Support/DataHelper.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Support/MongoClientUtil.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/TestData/WorkflowObjectTestData.cs
  tests/IntegrationTests/WorkflowManager.IntegrationTests/TestData/WorkflowRevisionTestData.cs
  tests/UnitTests/Common.Tests/Monai.Deploy.WorkflowManger.Common.Tests.csproj
  tests/UnitTests/Common.Tests/Services/WorkflowServiceTests.cs
  tests/UnitTests/TaskManager.Tests/TaskManagerTest.cs
  tests/UnitTests/WorkflowManager.Tests/Controllers/WorkflowsControllerTests.cs
  tests/UnitTests/WorkflowManager.Tests/Monai.Deploy.WorkflowManager.Tests.csproj
Labels: Awaiting Integration Tests

#184 Use gitleaks 1.6.0
  .github/workflows/security.yml
  NuGetDefense.json
Labels: build

#183 Dynamically load message broker plug-in
  doc/dependency_decisions.yml
  src/Configuration/Monai.Deploy.WorkflowManager.Configuration.csproj
  src/Configuration/packages.lock.json
  src/Contracts/Monai.Deploy.WorkflowManager.Contracts.csproj
  src/Database/Monai.Deploy.WorkflowManager.Database.csproj
  src/Database/packages.lock.json
  src/Monai.Deploy.WorkflowManager.Storage/Monai.Deploy.WorkflowManager.Storage.csproj
  src/Monai.Deploy.WorkflowManager.Storage/packages.lock.json
  src/PayloadListener/Monai.Deploy.WorkflowManager.PayloadListener.csproj
  src/PayloadListener/Services/EventPayloadRecieverService.cs
  src/PayloadListener/Services/PayloadListenerService.cs
  src/PayloadListener/packages.lock.json
  src/TaskManager/API/Monai.Deploy.WorkflowManager.TaskManager.API.csproj
  src/TaskManager/API/packages.lock.json
  src/TaskManager/Monai.Deploy.WorkflowManager.TaskManager.csproj
  src/TaskManager/Plug-ins/Argo/Monai.Deploy.WorkflowManager.TaskManager.Argo.csproj
  src/TaskManager/Plug-ins/Argo/packages.lock.json
  src/TaskManager/Runner/Program.cs
  src/TaskManager/Runner/appsettings.json
  src/TaskManager/TaskManager.cs
  src/TaskManager/packages.lock.json
  src/WorkflowExecuter/Monai.Deploy.WorkloadManager.WorkfowExecuter.csproj
  src/WorkflowExecuter/Services/WorkflowExecuterService.cs
  src/WorkflowExecuter/packages.lock.json
  src/WorkflowManager/Monai.Deploy.WorkflowManager.csproj
  src/WorkflowManager/Program.cs
  src/WorkflowManager/appsettings.Development.json
  src/WorkflowManager/appsettings.json
  src/WorkflowManager/packages.lock.json
  tests/IntegrationTests/WorkflowManager.IntegrationTests/Monai.Deploy.WorkflowManager.IntegrationTests.csproj
  tests/UnitTests/Configuration.Tests/Monai.Deploy.WorkflowManager.Configuration.Tests.csproj
  tests/UnitTests/PayloadListener.Tests/Monai.Deploy.WorkflowManager.PayloadListener.Tests.csproj
  tests/UnitTests/PayloadListener.Tests/Services/EventPayloadRecieverServiceTests.cs
  tests/UnitTests/TaskManager.Tests/TaskManagerTest.cs
  tests/UnitTests/WorkflowExecuter.Tests/Services/WorkflowExecuterServiceTests.cs
  tests/UnitTests/WorkflowManager.Tests/DummyMessagingService.cs
  tests/UnitTests/WorkflowManager.Tests/appsettings.json
  tests/UnitTests/WorkflowManager.Tests/packages.lock.json
Labels: refactor
