Repository Project-MONAI/monai-deploy-workflow-manager, pull requests merged in 2023-03, with the labels that each got.

#695 Switch to alpine based image for Callback app
  CallbackApp.Dockerfile
Labels: enhancement

#696 Resolve CVE-2022-1304
  CallbackApp.Dockerfile
Labels: security

#719 Release 0.1.4
  .github/.gitversion.yml
  .github/workflows/build.yml
  CallbackApp.Dockerfile
  docs/api/rest/task-manager/argo-template.md
  docs/changelog.md
  src/Monai.Deploy.WorkflowManager.sln
  src/Shared/Shared/PlugInAttribute.cs
  src/TaskManager/Plug-ins/Argo/ArgoClient.cs
  src/TaskManager/Plug-ins/Argo/ArgoPlugin.cs
  src/TaskManager/Plug-ins/Argo/Controllers/TemplateController.cs
  src/TaskManager/Plug-ins/Argo/Logging/Log.cs
  src/TaskManager/Plug-ins/Argo/Monai.Deploy.WorkflowManager.TaskManager.Argo.csproj
  src/TaskManager/Plug-ins/Argo/packages.lock.json
  src/TaskManager/TaskManager/Extensions/TaskManagerExtensions.cs
  src/TaskManager/TaskManager/Monai.Deploy.WorkflowManager.TaskManager.csproj
  src/TaskManager/TaskManager/Services/Http/Startup.cs
  src/TaskManager/TaskManager/appsettings.json
  src/TaskManager/TaskManager/packages.lock.json
  tests/UnitTests/TaskManager.Argo.Tests/ArgoPluginTest.cs
Labels: enhancement

#722 Release/0.1.5
  TaskManager.Dockerfile
Labels: enhancement, dependencies, docker

#724 Release/0.1.6
  .github/.gitversion.yml
  src/Shared/Shared/ValidationConstants.cs
  src/WorkflowManager/WorkflowManager/Validators/WorkflowValidator.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/Features/WorkflowApi.feature
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/StepDefinitions/WorkflowInstanceStepDefintions.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/TestData/WorkflowObjectTestData.cs
  tests/UnitTests/WorkflowManager.Tests/Controllers/WorkflowsControllerTests.cs
Labels: bug
