Repository Project-MONAI/monai-deploy-workflow-manager, pull requests merged in 2023-05, with the labels that each got.

#787 Release/0.1.13
  src/WorkflowManager/Database/Repositories/PayloadRepository.cs
  tests/UnitTests/WorkflowManager.Services.Tests/InformaticsGateway/InformaticsGatewayServiceTests.cs
Labels: bug

#793 Release/0.1.15
  guidelines/mwm-workflow-spec.md
Labels: documentation

#795 Release 0.1.16
  src/WorkflowManager/Common/Services/PayloadService.cs
  tests/UnitTests/Common.Tests/Services/PayloadServiceTests.cs
Labels: bug

#798 add tests for create workflow
  src/WorkflowManager/Monai.Deploy.WorkflowManager.Services/InformaticsGateway/InformaticsGatewayService.cs
  tests/UnitTests/WorkflowManager.Services.Tests/InformaticsGateway/InformaticsGatewayServiceTests.cs
  tests/UnitTests/WorkflowManager.Tests/Controllers/WorkflowsControllerTests.cs
Labels: bug

#805 Release 0.1.18
  src/WorkflowManager/Common/Services/PayloadService.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/Features/PayloadApi.feature
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/StepDefinitions/PayloadApiStepDefinitions.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/Support/Assertions.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/TestData/PayloadTestData.cs
  tests/IntegrationTests/WorkflowExecutor.IntegrationTests/TestData/WorkflowInstanceTestData.cs
  tests/UnitTests/Common.Tests/Services/PayloadServiceTests.cs
Labels: bug

#807 Release/0.1.19
  src/Shared/Shared/Wrappers/StatsPagedResponse.cs
  src/WorkflowManager/Common/Interfaces/IWorkflowService.cs
  src/WorkflowManager/Common/Services/WorkflowService.cs
  src/WorkflowManager/Database/Interfaces/ITaskExecutionStatsRepository.cs
  src/WorkflowManager/Database/Repositories/TaskExecutionStatsRepository.cs
  src/WorkflowManager/WorkflowManager/Controllers/TaskStatsController.cs
  src/WorkflowManager/WorkflowManager/Controllers/WorkflowsController.cs
  tests/IntegrationTests/TaskManager.IntegrationTests/Features/__snapshots__/ExecutionStatsFeature.ExecutionStatsForATaskAreReturned_Workflow_1_Task_2_.snap
  tests/IntegrationTests/TaskManager.IntegrationTests/Features/__snapshots__/ExecutionStatsFeature.ExecutionStatsForATaskAreReturned_workflow_1_task_1_.snap
  tests/UnitTests/Common.Tests/Services/WorkflowServiceTests.cs
  tests/UnitTests/WorkflowManager.Tests/Controllers/TaskExecutionStatsControllerTests.cs
  tests/UnitTests/WorkflowManager.Tests/Controllers/WorkflowsControllerTests.cs
Labels: bug

#811 added missed GetStatus method
  docs/changelog.md
  src/TaskManager/Plug-ins/AideClinicalReview/packages.lock.json
  src/TaskManager/Plug-ins/Argo/packages.lock.json
  src/TaskManager/Plug-ins/Email/EmailPlugin.cs
  src/TaskManager/TaskManager/packages.lock.json
Labels: enhancement
